type Collection {
    id: ID!
    name: String!
    slug: String!
    createdAt: String!
}

type Document {
    id: ID!
    title: String!
    content: String!
    tags: [String!]!
    collectionId: ID!
    isArchived: Boolean!
    createdAt: String!
}

type Query {
    collections: [Collection!]!
    collection(id: ID!): Collection

    documents(collectionId: ID): [Document!]!
    document(id: ID!): Document
}

input CreateCollectionInput {
    name: String!
    slug: String!
}

input CreateDocumentInput {
    title: String!
    content: String!
    tags: [String!]!
    collectionId: ID!
}

type Mutation {
    createCollection(input: CreateCollectionInput!): Collection!

    createDocument(input: CreateDocumentInput!): Document!
}